apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unsealer
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-unsealer
  namespace: vault
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs: [ "watch", "create", "get", "patch", "list" ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unsealer
  namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-unsealer
subjects:
  - kind: ServiceAccount
    name: vault-unsealer
    namespace: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-unsealer
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-unsealer
  template:
    metadata:
      labels:
        app: vault-unsealer
    spec:
      serviceAccountName: vault-unsealer
      containers:
        - name: vault-unsealer
          image: sakibalamin/vault-unsealer:1.0.0
          imagePullPolicy: Always