apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: vault
      app.kubernetes.io/name: vault
  namespaceSelector:
    matchNames:
      - vault
  endpoints:
    - interval: 30s
      path: /v1/sys/metrics
      params:
        format:
          - prometheus
      port: http
      scheme: http
      scrapeTimeout: 30s
      tlsConfig:
        insecureSkipVerify: true
