apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-auth
  namespace: app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
      # configures whether injection is explicitly enabled or disabled for a pod.
      # This should be set to a true or false value. Defaults to false.
        vault.hashicorp.com/agent-inject: 'true'

      # configures whether an init container is the only injected container.
      # If true, no sidecar container will be injected at runtime of the pod.
      # Enabling this option is recommended for workloads of type CronJob or Job
      # to ensure a clean pod termination.
        vault.hashicorp.com/agent-pre-populate-only: 'true'

      # this role name will be used to fetch db creds from the vault
        vault.hashicorp.com/role: 'app-creds-reader-role'
        
      # the path where we can generate dynamic db creds
        vault.hashicorp.com/agent-inject-secret-db-creds: 'database/creds/db-reader-role'
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/db-reader-role" -}}
          username={{ .Data.username }}
          password={{ .Data.password }}
          {{- end }}
    spec:
      containers:
        - name: app
          image: sakibalamin/app:1.0.0
          imagePullPolicy: Always
          args: ["serve"]
      serviceAccountName: app-auth
